# .goreleaser.yml
brews:
  -
    name: gocat
    tap:
      owner: fsuhrau
      name: homebrew-tap
    folder: Formula
    caveats: "adb logcat | gocat -tag com.yourcompany.appid -filter Networking"
    homepage: "https://github.com/fsuhrau/gocat"
    # Your app's description
    # Default is empty
    description: "gocat add coloring for logcat output"
    # license
    license: "MIT"
